# variables

- variables term vary
- you want to save some value at some place is called variable 
- variable and constant 

In [2]:
number = 230
number

230

In [4]:
number =234
number

234

first number is 230 and second number is 234 
second value varies from 230 thats why it is called a variables

**sum is math operation so it will works**


In [8]:
sum = 233
sum

233

#note

In [ ]:
but dont use sum as a variables.


**RULES OF VARIABLES**

- Uppercase and lowercase both can work(NAme= 200)
- Number as prefix will not work(123Name=314) not work
- Number as a suffix will work( Name21= 123) works
- Underscore will  work( namee_amsa=123) works
- Space between variable will not work(aman paudel=123) no works
- Keyword will not work( except sum)
  

